### ISSUE TITLE
Seems can't parse JSX syntax

### ISSUE THREAD

**Issue by MarekLacoAXA** [seek-oss/playroom#1]
Seems the webpack can't parse JSX syntax. On a minimalist example I get following error in JS console:

```
index.js:1 Uncaught Error: Module parse failed: Unexpected token (45:2)
You may need an appropriate loader to handle this file type.
| 
| render(
>   <Playroom
|     themes={themes}
|     components={components}
    at eval (index.js:1)
    at Object../node_modules/playroom/src/index.js (main.js:96)
    at __webpack_require__ (main.js:20)
    at main.js:84
    at main.js:87
```

**Comment by markdalgleish** [comment]
Are you able to share your minimal reproduction?

**Comment by MarekLacoAXA** [comment]
I followed the readme.md. Thanks!

/package.json
```
{
  "name": "playbook",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "playroom:start": "playroom start",
    "playroom:build": "playroom build"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "playroom": "^0.1.0"
  }
}
```


/playroom.config.js

```
module.exports = {
    title: 'Playroom',
    outputPath: './dist/playroom',
    components: './components',
    // themes: './src/themes',
    // frameComponent: './playroom/FrameComponent.js',
    widths: [320, 375, 768, 1024],
    exampleCode: `
    <Button>
      Hello World!
    </Button>
  `,
    webpackConfig: () => ({
        // Custom webpack config goes here...
    })
};
```

/components.js

```
module.exports = {
    Button: () => {
        return (
            <button>
                button
            </button>
        )
    }
    // etc...
};
```

**Comment by markdalgleish** [comment]
Ah, turns out I made a silly mistake in the webpack config. Just published a fix as v0.1.1. Thanks for raising this issue!

**Comment by jamesmckenzie** [comment]
I'm running the example from above on v0.1.1 and now getting this error:

```
Uncaught Error: Module parse failed: Unexpected token (5:11)
You may need an appropriate loader to handle this file type.
| module.exports = {
|   Button: () => {
>     return <button>button</button>;
|   }
|   // etc...
    at eval (components.js:1)
    at Object../components.js (main.js:96)
    at __webpack_require__ (main.js:20)
    at eval (index.js?e33e:11)
    at Module../node_modules/playroom/src/index.js (main.js:2058)
    at __webpack_require__ (main.js:20)
    at main.js:84
    at main.js:87
```

**Comment by httpete-ire** [comment]
I tried to get the `seek style guide` example up and running and I get the error below in the console after running `playroom start`

<img width="988" alt="screenshot 2018-10-29 at 22 40 12" src="https://user-images.githubusercontent.com/1556430/47684679-9e91cf00-dbcb-11e8-80ae-c80ae3b3e236.png">

**Comment by markdalgleish** [comment]
Have you pulled the latest code? Pretty sure this is already fixed.

**Comment by httpete-ire** [comment]
Looking in the `playroom` package in `node_modules` the version is `v0.1.1` but I cant see the changes in the `lib/makeWebpackConfig.js` file 🤔

**Comment by dburles** [comment]
Same issue here, also on 0.1.1

**Comment by markdalgleish** [comment]
We don't yet provide default webpack config for your code, but we're hoping to add this feature soon.

**Comment by dburles** [comment]
Hey @markdalgleish I feel like I must be missing something but I am still seeing this same error on the latest version with a basic configuration without any custom webpack config

**Comment by pascalduez** [comment]
@dburles  Something in this vein should do it.

```js
webpackConfig: () => ({
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: [
          {
            loader: 'babel-loader',
            options: {
              presets: [['@babel/env', { modules: false }], '@babel/react'],
            },
          },
        ],
      },
    ],
  },
})
````

**Comment by dburles** [comment]
thanks @pascalduez !

**Comment by markdalgleish** [comment]
FYI, as of v0.5.1, you no longer need to apply webpack config like @pascalduez's example. If custom webpack config isn't provided, your project code is now run through Babel + preset-env + preset-react.
